"""Universal, domain-neutral graph programming primitives.

``browsergraph`` is one runtime adapter and demonstration domain.  This package
contains the semantic model, compiler, search policies, and evidence contracts
that are intended to apply to any typed graph-programming problem.
"""
from solutiongraph.compiler import Compiler
from solutiongraph.errors import Diagnostic, ValidationError
from solutiongraph.evidence import (
    EvidenceLedger,
    ExperimentDesign,
    NodeRunReceipt,
    Objective,
    RouteAggregate,
    RunReceipt,
    learn_observational_beliefs,
    pareto_front,
)
from solutiongraph.model import (
    SEMANTIC_MODEL_VERSION,
    AdmissionDecision,
    AdmittedSpace,
    Candidate,
    Cardinality,
    Determinism,
    Edge,
    FailureMode,
    ForbiddenCombination,
    FrozenPlan,
    GraphInput,
    GraphOutput,
    Idempotency,
    NodeSpec,
    ParameterSpec,
    PlanBinding,
    Port,
    ProgramGraph,
    Registry,
    ResourceClaim,
    SemanticSlot,
    SlotKind,
    ValueType,
    canonical_json,
    sha256_digest,
)
from solutiongraph.search import (
    BeliefModel,
    CandidateWeight,
    InteractionWeight,
    RouteProposal,
    SearchBudget,
    SearchEngine,
    SearchMode,
    SearchReport,
    cartesian_routes,
)

__version__ = "0.1.0"

__all__ = [
    "SEMANTIC_MODEL_VERSION",
    "AdmittedSpace",
    "AdmissionDecision",
    "BeliefModel",
    "Candidate",
    "CandidateWeight",
    "Cardinality",
    "Compiler",
    "Determinism",
    "Diagnostic",
    "Edge",
    "EvidenceLedger",
    "ExperimentDesign",
    "FailureMode",
    "ForbiddenCombination",
    "FrozenPlan",
    "GraphInput",
    "GraphOutput",
    "Idempotency",
    "InteractionWeight",
    "NodeRunReceipt",
    "NodeSpec",
    "Objective",
    "ParameterSpec",
    "PlanBinding",
    "Port",
    "ProgramGraph",
    "Registry",
    "ResourceClaim",
    "RouteAggregate",
    "RouteProposal",
    "RunReceipt",
    "SearchBudget",
    "SearchEngine",
    "SearchMode",
    "SearchReport",
    "SemanticSlot",
    "SlotKind",
    "ValidationError",
    "ValueType",
    "canonical_json",
    "cartesian_routes",
    "learn_observational_beliefs",
    "pareto_front",
    "sha256_digest",
]
