"""Six model families on identical inputs, and the answer that depends on the data.

The question "which model should we use" is usually settled by preference and
then defended by a benchmark run afterwards. This pack makes the family a
**candidate for one step** — everything upstream of it identical, everything
downstream identical — so the comparison measures the family and nothing else.

    from browsergraph import packs
    print(packs.get("models").solve().text())

Two data-generating processes, six families, RMSE on held-out rows — lower is
better, and `removed` is the fraction of the null control's error the family
actually got rid of. Measured, by a test that runs every route:

    family          linear truth  removed    threshold truth  removed
    fit.constant         73.8        —             54.6          —
    fit.linear            5.2       93%            33.2         39%
    fit.mlp               7.4       90%            19.8         64%
    fit.boosted          15.5       79%            19.5         64%
    fit.tree             39.6       46%            28.7         47%
    fit.attention        43.1       42%            37.2         32%

**There is no winner column.** The linear model removes 93% of the error on data
generated by an additive rule and 39% on data generated by a threshold and an
interaction — where boosted trees and a small network remove 64%. Both results
are obvious in hindsight and neither is knowable from the model list. Any
ranking of families that does not name the data-generating process is a ranking
of somebody's datasets.

`fit.constant` is the null control and the most important row in the table. It
predicts the training mean and nothing else, so a family that does not clearly
beat it has learned nothing — and **the number to beat is different for each
dataset** (73.8 and 54.6), which is why an absolute RMSE threshold carried
between projects means nothing at all. `compare.interval` therefore reports
every score against the constant with a bootstrap interval, and will say "this
decision does not matter" rather than crown a winner on a difference inside the
noise.

`fit.attention` is a single head over the columns — learned query, per-column
keys and values, softmax weights — and it is **fifth of six on both datasets**.
That is the expected and correct result at this size, and it is in the pack for
that reason: on a few hundred rows of tabular data a regularised linear model
and boosted trees are the honest baselines, and an attention model that beat
them here would be evidence of a bug rather than of progress.

Two findings fell out of building this and are documented where they happened
rather than smoothed away. A **depth-three tree scored worse than the null
control** on the threshold data, because one-hot encoding drops a reference
level and the tree then needs two splits to isolate the dropped category — the
encoding a linear model requires is not the encoding a tree requires. And
**boosting depth-one stumps is an additive model**, so it could not express the
size-and-kind interaction any better than the linear fit could; the base learner
is at depth two for that reason, which is a decision and not a default.

`prepare` is a single step shared by every family, which is the discipline the
whole comparison rests on. Its two candidates differ only in whether the numeric
columns are standardised, and the statistics come from the training half — the
transformer travels with the fold, so nothing downstream can recompute them
against the rows it is being scored on.

Standard library: Gaussian elimination for the linear fit, greedy
variance-reduction splits for the tree, gradient descent by hand for the two
networks. No numpy, seeded throughout.
"""
from __future__ import annotations

import math
import random
import statistics
from typing import Any

from browsergraph.execute import Runtime
from browsergraph.manifest import NodeManifest, PortSpec
from browsergraph.templates import get as _template
from browsergraph.workbench import (
    NodeCandidate,
    OptimizationObjective,
    OptimizationProfile,
    WorkbenchDefinition,
)

TEMPLATE = "model.bakeoff"
SUMMARY = "compare linear, tree, boosted, network and attention on one preparation"

FILLING: dict[str, list[str]] = {
    "load":     ["load.linear_truth", "load.threshold_truth"],
    "split":    ["split.random", "split.ordered"],
    "prepare":  ["prepare.standardised", "prepare.onehot"],
    "fit":      ["fit.linear", "fit.tree", "fit.boosted", "fit.mlp",
                 "fit.attention", "fit.constant"],
    "evaluate": ["evaluate.rmse", "evaluate.mae"],
    "compare":  ["compare.interval", "compare.best"],
}

KINDS = ("house", "flat", "studio")
KIND_EFFECT = {"house": 60.0, "flat": 0.0, "studio": -35.0}


def _node(node_id: str, capability: str, takes, gives, *,
          description: str, **extra) -> NodeManifest:
    return NodeManifest(
        id=node_id, kind=node_id.split(".")[-1], description=description,
        capabilities=(capability,),
        inputs=tuple(PortSpec(n, t) for n, t in takes),
        outputs=tuple(PortSpec(n, t) for n, t in gives),
        metrics={"source": "illustrative-prior", "quality": 0.9},
        **extra)


NODES: tuple[NodeManifest, ...] = (
    _node("load.linear_truth", "data.read", [], [("out", "Frame")],
          description="The target is an additive function of the columns. "
                      "What a linear model is for."),
    _node("load.threshold_truth", "data.read", [], [("out", "Frame")],
          description="The target jumps at a threshold and depends on an "
                      "interaction. What trees are for, and additivity cannot "
                      "express."),

    _node("split.random", "data.split", [("in", "Frame")],
          [("train", "Frame"), ("valid", "Frame")],
          description="Shuffle, then cut."),
    _node("split.ordered", "data.split", [("in", "Frame")],
          [("train", "Frame"), ("valid", "Frame")],
          description="First 70%. These rows have no order, so the two "
                      "should agree — which makes them a check on each other "
                      "rather than a choice."),

    _node("prepare.standardised", "feature.prepare",
          [("train", "Frame"), ("valid", "Frame")], [("out", "Fold")],
          description="One-hot the category and z-score the numbers, using "
                      "training statistics only. The networks need it; the "
                      "trees are indifferent."),
    _node("prepare.onehot", "feature.prepare",
          [("train", "Frame"), ("valid", "Frame")], [("out", "Fold")],
          description="One-hot only, numbers left raw. Fine for trees, and it "
                      "makes the gradient methods worse — which is a fact "
                      "about the preparation, not about the families."),

    _node("fit.constant", "model.fit", [("in", "Fold")], [("out", "Model")],
          description="Predicts the training mean. The null control: a family "
                      "that does not clearly beat this has learned nothing, "
                      "and the bar is different on every dataset."),
    _node("fit.linear", "model.fit", [("in", "Fold")], [("out", "Model")],
          description="Ridge-regularised least squares, solved directly."),
    _node("fit.tree", "model.fit", [("in", "Fold")], [("out", "Model")],
          description="A depth-four regression tree, greedy on variance "
                      "reduction. Expresses thresholds and interactions, and "
                      "approximates a straight line as a staircase."),
    _node("fit.boosted", "model.fit", [("in", "Fold")], [("out", "Model")],
          description="Sixty depth-two trees at a small learning rate. The "
                      "honest strong baseline for tabular data — and depth "
                      "two rather than one because stumps cannot express an "
                      "interaction at all."),
    _node("fit.mlp", "model.fit", [("in", "Fold")], [("out", "Model")],
          description="One hidden layer of six tanh units, full-batch "
                      "gradient descent."),
    _node("fit.attention", "model.fit", [("in", "Fold")], [("out", "Model")],
          description="A single attention head over the columns: a learned "
                      "query, a key and a value per column, softmax weights. "
                      "Not a transformer, and it says so."),

    _node("evaluate.rmse", "model.evaluate",
          [("model", "Model"), ("fold", "Fold")], [("out", "Score")],
          description="Root mean squared error on the held-out half."),
    _node("evaluate.mae", "model.evaluate",
          [("model", "Model"), ("fold", "Fold")], [("out", "Score")],
          description="Mean absolute error. Ranks differently when the errors "
                      "are skewed, which is worth knowing before choosing."),

    _node("compare.interval", "model.compare", [("in", "Score")],
          [("out", "Report")],
          description="Bootstrap interval on the score, against the constant "
                      "baseline. Says 'this decision does not matter' when "
                      "that is the truth."),
    _node("compare.best", "model.compare", [("in", "Score")],
          [("out", "Report")],
          description="Reports the number. What a leaderboard does."),
)


def workbench() -> WorkbenchDefinition:
    template = _template(TEMPLATE)
    bench = template.instantiate(FILLING)
    return WorkbenchDefinition(
        title=template.title, task=template.task,
        stages=bench.stages, edges=bench.edges, nodes=NODES,
        candidates=tuple(NodeCandidate(id=n.id, node_id=n.id) for n in NODES),
        optimization_profiles=(OptimizationProfile(
            id="p.models", name="Beat the null control by more than the noise",
            objectives=(OptimizationObjective("quality", "maximize", 1.0),)),),
        metadata=dict(bench.metadata, pack="models"),
    ).assert_valid()


# --- the data ---------------------------------------------------------------

def _rows(kind_of_truth: str, n: int = 200, seed: int = 3) -> list[dict[str, Any]]:
    rng = random.Random(seed)
    rows = []
    for _ in range(n):
        kind = rng.choice(KINDS)
        size = round(rng.uniform(0.5, 4.0), 3)
        age = round(rng.uniform(0.0, 60.0), 1)
        if kind_of_truth == "linear":
            price = 40 * size + 3 * age + KIND_EFFECT[kind]
        else:
            # A step and an interaction. No additive model can express this,
            # and every tree can.
            price = 120.0 if (size > 2.0 and kind == "house") else 30.0
            price += 80.0 if age > 40 else 0.0
        rows.append({"size": size, "age": age, "kind": kind,
                     "price": round(price + rng.gauss(0, 5), 3)})
    return rows


# --- preparation ------------------------------------------------------------

FEATURES = ("size", "age", "kind=flat", "kind=studio")


def _vector(row: dict[str, Any]) -> list[float]:
    return [float(row["size"]), float(row["age"]),
            1.0 if row["kind"] == "flat" else 0.0,
            1.0 if row["kind"] == "studio" else 0.0]


#: Fits are pure functions of (fold, family), and the exhaustive route test
#: asks for the same one many times over. Memoising makes that test seconds
#: rather than minutes and changes no result — the key is derived from the
#: data, so two folds that differ anywhere get different fits.
_FITS: dict[tuple[str, str], dict[str, Any]] = {}


def _memoised(family: str, fold, build):
    key = (fold["signature"], family)
    if key not in _FITS:
        _FITS[key] = build(fold)
    return _FITS[key]


def _prepare(train, valid, *, standardise: bool) -> dict[str, Any]:
    x_train = [_vector(r) for r in train]
    x_valid = [_vector(r) for r in valid]
    y_train = [float(r["price"]) for r in train]
    y_valid = [float(r["price"]) for r in valid]

    stats = None
    if standardise:
        # From the training half only. The numbers travel with the fold, so
        # nothing downstream can recompute them against the validation rows.
        stats = []
        for column in range(len(FEATURES)):
            values = [row[column] for row in x_train]
            mean = statistics.fmean(values)
            spread = statistics.pstdev(values) or 1.0
            stats.append((mean, spread))
        x_train = [[(v - m) / s for v, (m, s) in zip(row, stats, strict=True)]
                   for row in x_train]
        x_valid = [[(v - m) / s for v, (m, s) in zip(row, stats, strict=True)]
                   for row in x_valid]

    baseline = statistics.fmean(y_train)
    return {"x_train": x_train, "y_train": y_train, "x_valid": x_valid,
            "y_valid": y_valid, "features": list(FEATURES),
            "standardised": standardise,
            "signature": f"{standardise}|{len(x_train)}|"
                         f"{round(sum(y_train), 4)}|"
                         f"{round(sum(row[0] for row in x_train), 4)}",
            "fitted_on": len(x_train),
            "statistics": stats,
            "baseline_prediction": baseline,
            "baseline_rmse": _rmse([baseline] * len(y_valid), y_valid),
            "baseline_mae": _mae([baseline] * len(y_valid), y_valid)}


def _rmse(predicted, truth) -> float:
    if not truth:
        return 0.0
    return math.sqrt(statistics.fmean(
        [(p - t) ** 2 for p, t in zip(predicted, truth, strict=True)]))


def _mae(predicted, truth) -> float:
    if not truth:
        return 0.0
    return statistics.fmean([abs(p - t)
                             for p, t in zip(predicted, truth, strict=True)])


# --- the families -----------------------------------------------------------

def _fit_linear(fold) -> dict[str, Any]:
    matrix = [[1.0, *row] for row in fold["x_train"]]
    weights = _solve(matrix, fold["y_train"], ridge=1e-3)
    return {"family": "linear", "weights": weights,
            "names": ["intercept", *fold["features"]]}


def _solve(matrix, target, ridge: float) -> list[float]:
    width = len(matrix[0])
    gram = [[sum(r[i] * r[j] for r in matrix) + (ridge if i == j else 0.0)
             for j in range(width)] for i in range(width)]
    rhs = [sum(r[i] * t for r, t in zip(matrix, target, strict=True))
           for i in range(width)]
    for i in range(width):
        pivot = max(range(i, width), key=lambda r: abs(gram[r][i]))
        if abs(gram[pivot][i]) < 1e-12:
            continue
        gram[i], gram[pivot] = gram[pivot], gram[i]
        rhs[i], rhs[pivot] = rhs[pivot], rhs[i]
        for r in range(i + 1, width):
            factor = gram[r][i] / gram[i][i]
            for c in range(i, width):
                gram[r][c] -= factor * gram[i][c]
            rhs[r] -= factor * rhs[i]
    weights = [0.0] * width
    for i in reversed(range(width)):
        if abs(gram[i][i]) < 1e-12:
            continue
        weights[i] = (rhs[i] - sum(gram[i][j] * weights[j]
                                   for j in range(i + 1, width))) / gram[i][i]
    return weights


def _best_split(rows, target) -> tuple[int, float, float] | None:
    """The split that most reduces total squared error. Greedy, and that is
    the whole algorithm — a tree is this, recursively."""
    best = None
    for column in range(len(rows[0])):
        values = sorted({row[column] for row in rows})
        for left, right in zip(values, values[1:], strict=False):
            threshold = (left + right) / 2
            below = [t for row, t in zip(rows, target, strict=True)
                     if row[column] <= threshold]
            above = [t for row, t in zip(rows, target, strict=True)
                     if row[column] > threshold]
            if len(below) < 3 or len(above) < 3:
                continue
            error = (sum((t - statistics.fmean(below)) ** 2 for t in below)
                     + sum((t - statistics.fmean(above)) ** 2 for t in above))
            if best is None or error < best[2]:
                best = (column, threshold, error)
    return best


def _grow(rows, target, depth: int) -> dict[str, Any]:
    if depth <= 0 or len(rows) < 6 or len(set(target)) == 1:
        return {"leaf": statistics.fmean(target) if target else 0.0}
    found = _best_split(rows, target)
    if found is None:
        return {"leaf": statistics.fmean(target)}
    column, threshold, _ = found
    below = [(r, t) for r, t in zip(rows, target, strict=True)
             if r[column] <= threshold]
    above = [(r, t) for r, t in zip(rows, target, strict=True)
             if r[column] > threshold]
    return {"column": column, "threshold": threshold,
            "left": _grow([r for r, _ in below], [t for _, t in below], depth - 1),
            "right": _grow([r for r, _ in above], [t for _, t in above], depth - 1)}


def _tree_predict(node, row) -> float:
    while "leaf" not in node:
        node = node["left"] if row[node["column"]] <= node["threshold"] \
            else node["right"]
    return node["leaf"]


#: Four, not three, and the reason is worth knowing. One-hot encoding drops a
#: reference level — correct for a linear model, which would otherwise have a
#: collinear column — and that leaves a tree needing *two* splits to isolate
#: the dropped category (`flat == 0` and `studio == 0`). A depth-three tree on
#: this data spends three of its splits reaching a threshold it could have
#: reached in two, and scores worse than the null control. The encoding a
#: linear model needs is not the encoding a tree needs, and sharing one
#: preparation across families is a real cost as well as the only way to make
#: the comparison mean anything.
TREE_DEPTH = 4


def _fit_tree(fold) -> dict[str, Any]:
    return {"family": "tree", "depth": TREE_DEPTH,
            "tree": _grow(fold["x_train"], fold["y_train"], TREE_DEPTH)}


def _fit_boosted(fold, rounds: int = 60, rate: float = 0.15,
                 depth: int = 2) -> dict[str, Any]:
    """Boosted trees, at depth two rather than one.

    Depth-one stumps are the textbook illustration and they are an **additive
    model**: each stump reads one column, so no number of them can express
    "large *and* a house". Boosting stumps on this pack's threshold dataset
    scores worse than a single tree, which is the correct behaviour of an
    additive method on an interaction and is exactly why the depth of the base
    learner is a decision rather than a detail.
    """
    base = statistics.fmean(fold["y_train"])
    residual = [y - base for y in fold["y_train"]]
    stumps = []
    for _ in range(rounds):
        stump = _grow(fold["x_train"], residual, depth)
        stumps.append(stump)
        for index, row in enumerate(fold["x_train"]):
            residual[index] -= rate * _tree_predict(stump, row)
    return {"family": "boosted", "base": base, "rate": rate, "stumps": stumps}


def _fit_mlp(fold, hidden: int = 6, epochs: int = 400,
             rate: float = 0.15) -> dict[str, Any]:
    rng = random.Random(19)
    width = len(fold["features"])
    # The target is centred and scaled so one learning rate works whether or
    # not the inputs were standardised. Without this the un-standardised route
    # diverges and the comparison becomes a comparison of learning rates.
    mean = statistics.fmean(fold["y_train"])
    spread = statistics.pstdev(fold["y_train"]) or 1.0
    target = [(y - mean) / spread for y in fold["y_train"]]
    scale = [1.0 / (max(abs(r[c]) for r in fold["x_train"]) or 1.0)
             for c in range(width)]
    inputs = [[v * s for v, s in zip(row, scale, strict=True)]
              for row in fold["x_train"]]

    w1 = [[rng.gauss(0, 0.5) for _ in range(width)] for _ in range(hidden)]
    b1 = [0.0] * hidden
    w2 = [rng.gauss(0, 0.5) for _ in range(hidden)]
    b2 = 0.0
    n = len(inputs) or 1

    for _ in range(epochs):
        g_w1 = [[0.0] * width for _ in range(hidden)]
        g_b1 = [0.0] * hidden
        g_w2 = [0.0] * hidden
        g_b2 = 0.0
        for row, truth in zip(inputs, target, strict=True):
            hid = [math.tanh(sum(w * x for w, x in zip(w1[j], row, strict=True))
                             + b1[j]) for j in range(hidden)]
            out = sum(w * h for w, h in zip(w2, hid, strict=True)) + b2
            error = out - truth
            g_b2 += error
            for j in range(hidden):
                g_w2[j] += error * hid[j]
                delta = error * w2[j] * (1 - hid[j] ** 2)
                g_b1[j] += delta
                for c in range(width):
                    g_w1[j][c] += delta * row[c]
        b2 -= rate * g_b2 / n
        for j in range(hidden):
            w2[j] -= rate * g_w2[j] / n
            b1[j] -= rate * g_b1[j] / n
            for c in range(width):
                w1[j][c] -= rate * g_w1[j][c] / n

    return {"family": "mlp", "w1": w1, "b1": b1, "w2": w2, "b2": b2,
            "scale": scale, "mean": mean, "spread": spread, "hidden": hidden}


def _fit_attention(fold, epochs: int = 400, rate: float = 0.15) -> dict[str, Any]:
    """A single attention head over the columns.

    Each column gets a key and a value; a learned query is scored against every
    key; the softmax of those scores weights the per-column contributions. That
    is attention in its smallest honest form — one head, no positions, no
    layers, nothing stacked. Calling it a transformer would be a lie and
    calling it linear would be one too: the weights depend on the learned
    query, so which columns matter is itself learned.
    """
    rng = random.Random(19)
    width = len(fold["features"])
    mean = statistics.fmean(fold["y_train"])
    spread = statistics.pstdev(fold["y_train"]) or 1.0
    target = [(y - mean) / spread for y in fold["y_train"]]
    scale = [1.0 / (max(abs(r[c]) for r in fold["x_train"]) or 1.0)
             for c in range(width)]
    inputs = [[v * s for v, s in zip(row, scale, strict=True)]
              for row in fold["x_train"]]

    keys = [rng.gauss(0, 0.5) for _ in range(width)]
    values = [rng.gauss(0, 0.5) for _ in range(width)]
    query = 1.0
    bias = 0.0
    n = len(inputs) or 1

    for _ in range(epochs):
        g_keys = [0.0] * width
        g_values = [0.0] * width
        g_query = 0.0
        g_bias = 0.0
        for row, truth in zip(inputs, target, strict=True):
            scores = [query * k for k in keys]
            top = max(scores)
            exps = [math.exp(s - top) for s in scores]
            total = sum(exps) or 1.0
            weights = [e / total for e in exps]
            parts = [values[c] * row[c] for c in range(width)]
            out = sum(w * p for w, p in zip(weights, parts, strict=True)) + bias
            error = out - truth

            g_bias += error
            # d out / d weight_c = parts[c]; softmax Jacobian folded in below.
            d_weights = [error * parts[c] for c in range(width)]
            weighted = sum(w * d for w, d in zip(weights, d_weights, strict=True))
            d_scores = [weights[c] * (d_weights[c] - weighted)
                        for c in range(width)]
            for c in range(width):
                g_values[c] += error * weights[c] * row[c]
                g_keys[c] += d_scores[c] * query
                g_query += d_scores[c] * keys[c]

        bias -= rate * g_bias / n
        query -= rate * g_query / n
        for c in range(width):
            keys[c] -= rate * g_keys[c] / n
            values[c] -= rate * g_values[c] / n

    return {"family": "attention", "keys": keys, "values": values,
            "query": query, "bias": bias, "scale": scale, "mean": mean,
            "spread": spread}


def _fit_constant(fold) -> dict[str, Any]:
    return {"family": "constant", "value": fold["baseline_prediction"]}


def _predict(model, row) -> float:
    family = model["family"]
    if family == "constant":
        return model["value"]
    if family == "linear":
        return sum(w * x for w, x in zip(model["weights"], [1.0, *row],
                                         strict=True))
    if family == "tree":
        return _tree_predict(model["tree"], row)
    if family == "boosted":
        return model["base"] + model["rate"] * sum(
            _tree_predict(stump, row) for stump in model["stumps"])

    scaled = [v * s for v, s in zip(row, model["scale"], strict=True)]
    if family == "mlp":
        hid = [math.tanh(sum(w * x for w, x in zip(model["w1"][j], scaled,
                                                   strict=True))
                         + model["b1"][j]) for j in range(model["hidden"])]
        out = sum(w * h for w, h in zip(model["w2"], hid, strict=True)) \
            + model["b2"]
    else:                                       # attention
        scores = [model["query"] * k for k in model["keys"]]
        top = max(scores)
        exps = [math.exp(s - top) for s in scores]
        total = sum(exps) or 1.0
        weights = [e / total for e in exps]
        out = sum(w * model["values"][c] * scaled[c]
                  for c, w in enumerate(weights)) + model["bias"]
    return out * model["spread"] + model["mean"]


def _evaluate(model, fold, *, metric: str) -> dict[str, Any]:
    predicted = [_predict(model, row) for row in fold["x_valid"]]
    score = _rmse(predicted, fold["y_valid"]) if metric == "rmse" \
        else _mae(predicted, fold["y_valid"])
    baseline = fold["baseline_rmse"] if metric == "rmse" else fold["baseline_mae"]
    return {"family": model["family"], "metric": metric, "score": score,
            "baseline": baseline, "n": len(fold["y_valid"]),
            "lower_is_better": True,
            "residuals": [p - t for p, t in zip(predicted, fold["y_valid"],
                                                strict=True)],
            "standardised": fold["standardised"]}


def _compare(score: dict[str, Any], *, interval: bool) -> dict[str, Any]:
    beat = score["baseline"] - score["score"]
    report = {"family": score["family"], "metric": score["metric"],
              "score": score["score"], "baseline": score["baseline"],
              "beats_null_by": beat}
    if not interval:
        report["text"] = (f"{score['family']} {score['metric']} "
                          f"{score['score']:.2f}")
        report["decision_matters"] = None
        return report

    rng = random.Random(101)
    residuals = score["residuals"] or [0.0]
    draws = []
    for _ in range(120):
        sample = [rng.choice(residuals) for _ in residuals]
        draws.append(math.sqrt(statistics.fmean([r ** 2 for r in sample]))
                     if score["metric"] == "rmse"
                     else statistics.fmean([abs(r) for r in sample]))
    draws.sort()
    low, high = draws[len(draws) // 20], draws[-max(1, len(draws) // 20)]
    matters = beat > (high - low)
    report.update({
        "interval": [low, high], "half_width": (high - low) / 2,
        "decision_matters": matters,
        "text": (f"{score['family']} {score['metric']} {score['score']:.2f} "
                 f"[{low:.2f}, {high:.2f}] against a null of "
                 f"{score['baseline']:.2f} — "
                 + ("a real improvement" if matters else
                    "inside the spread, so this decision does not matter"))})
    return report


def runtime(**_: Any) -> Runtime:
    linear, threshold = _rows("linear"), _rows("threshold")

    def split(rows, shuffle):
        ordered = list(rows)
        if shuffle:
            random.Random(7).shuffle(ordered)
        cut = int(len(ordered) * 0.7)
        return {"train": ordered[:cut], "valid": ordered[cut:]}

    return Runtime({
        "load.linear_truth": lambda **kw: linear,
        "load.threshold_truth": lambda **kw: threshold,
        "split.random": lambda **kw: split(kw["in"], True),
        "split.ordered": lambda **kw: split(kw["in"], False),
        "prepare.standardised": lambda **kw: _prepare(kw["train"], kw["valid"],
                                                      standardise=True),
        "prepare.onehot": lambda **kw: _prepare(kw["train"], kw["valid"],
                                                standardise=False),
        "fit.constant": lambda **kw: _fit_constant(kw["in"]),
        "fit.linear": lambda **kw: _memoised("linear", kw["in"], _fit_linear),
        "fit.tree": lambda **kw: _memoised("tree", kw["in"], _fit_tree),
        "fit.boosted": lambda **kw: _memoised("boosted", kw["in"], _fit_boosted),
        "fit.mlp": lambda **kw: _memoised("mlp", kw["in"], _fit_mlp),
        "fit.attention": lambda **kw: _memoised("attention", kw["in"],
                                                _fit_attention),
        "evaluate.rmse": lambda **kw: _evaluate(kw["model"], kw["fold"],
                                                metric="rmse"),
        "evaluate.mae": lambda **kw: _evaluate(kw["model"], kw["fold"],
                                               metric="mae"),
        "compare.interval": lambda **kw: _compare(kw["in"], interval=True),
        "compare.best": lambda **kw: _compare(kw["in"], interval=False),
    })


def example() -> dict[str, Any]:
    return {}


def beats_the_null(run) -> tuple[bool, float]:
    """How much of the null baseline's error the family removed.

    Expressed as a fraction so the two datasets and the two metrics are on one
    scale — an absolute RMSE is not comparable across either, and a leaderboard
    that mixes them is comparing the difficulty of the data.
    """
    if not run.ok:
        return False, 0.0
    report = run.output("compare")
    baseline = report["baseline"] or 1.0
    removed = max(0.0, report["beats_null_by"] / baseline)
    return report["beats_null_by"] > 0, removed
